Traceback (most recent call last):
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/gwatts/code/diff-prog-intro/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
params = train(model=model,
    key = key, 
    epochs = 2000,
    training_data=training_data,
    training_truth=training_truth)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mArgumentError[0m                             Traceback (most recent call last)
Cell [0;32mIn [6], line 1[0m
[0;32m----> 1[0m params [38;5;241m=[39m [43mtrain[49m[43m([49m[43mmodel[49m[38;5;241;43m=[39;49m[43mmodel[49m[43m,[49m
[1;32m      2[0m [43m    [49m[43mkey[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mkey[49m[43m,[49m[43m [49m
[1;32m      3[0m [43m    [49m[43mepochs[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;241;43m2000[39;49m[43m,[49m
[1;32m      4[0m [43m    [49m[43mtraining_data[49m[38;5;241;43m=[39;49m[43mtraining_data[49m[43m,[49m
[1;32m      5[0m [43m    [49m[43mtraining_truth[49m[38;5;241;43m=[39;49m[43mtraining_truth[49m[43m)[49m

File [0;32m~/code/diff-prog-intro/book/jax_helpers.py:64[0m, in [0;36mtrain[0;34m(model, key, epochs, training_data, training_truth, learning_rate)[0m
[1;32m     59[0m [38;5;28;01mdef[39;00m [38;5;21mtrain[39m(
[1;32m     60[0m     model, key, epochs, training_data, training_truth, learning_rate[38;5;241m=[39m[38;5;241m0.002[39m
[1;32m     61[0m ) [38;5;241m-[39m[38;5;241m>[39m Dict:
[1;32m     62[0m     [38;5;66;03m# Initialize the weights[39;00m
[1;32m     63[0m     key, _ [38;5;241m=[39m jax[38;5;241m.[39mrandom[38;5;241m.[39msplit(key)
[0;32m---> 64[0m     params [38;5;241m=[39m model[38;5;241m.[39minit(key, training_data)
[1;32m     66[0m     [38;5;66;03m# Init the optimizer[39;00m
[1;32m     67[0m     opt_init, opt_update [38;5;241m=[39m optax[38;5;241m.[39mchain(optax[38;5;241m.[39madam(learning_rate), optax[38;5;241m.[39mzero_nans())

File [0;32m/usr/lib/python3.8/ctypes/__init__.py:507[0m, in [0;36mcast[0;34m(obj, typ)[0m
[1;32m    506[0m [38;5;28;01mdef[39;00m [38;5;21mcast[39m(obj, typ):
[0;32m--> 507[0m     [38;5;28;01mreturn[39;00m [43m_cast[49m[43m([49m[43mobj[49m[43m,[49m[43m [49m[43mobj[49m[43m,[49m[43m [49m[43mtyp[49m[43m)[49m

[0;31mArgumentError[0m: argument 1: <class 'TypeError'>: wrong type
ArgumentError: argument 1: <class 'TypeError'>: wrong type

